apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_ingress_controller_requests{exported_namespace="microservices"}'
      resources:
        overrides:
          exported_service:
            resource: service
      name:
        as: "gateway_rps"
      metricsQuery: 'sum(rate(nginx_ingress_controller_requests{exported_service="gateway-service"}[1m]))'