apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_ingress_controller_request_duration_seconds_count{exported_namespace="microservices"}'
      resources:
        overrides:
          exported_service:
            resource: service
      name:
        matches: "^(.*)$"
        as: "gateway_requests_per_second"
      metricsQuery: 'sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_service="gateway-service",status="200"}[1m]))'